sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: GPAqG52IjRIRmul5z1FBTd9d0p92UdCBCy9Eme2NZN0qKNWePMqeG+KNuXJzixWGkgXbMxI4D7HSMqxmYKBK+KhzF2Y847QjxDLaQB71IeGhNFwSn3COtEA4xQ8Rp2h+6i6qNAdOYGk1oyKqtJrQIafa2jmX+6uPawjBnTMwOyy3jEz3wG3Rj+YXKNMtUHX9LeaXY0M/k0LE1uM4SppswNXkNbNIpqzkwjqFSoPzYa4AlKkTOlzfeOwiBMz1b+B6FlodozhUMWq1yQAxSsEvb0Q6r+QhaQQ2BkUymzpzHUIDs7IWnpeikEIXODfX7dWwx14qJSzj6333CUVAP6WwtQwuk39/40I/GbhEuFK+oTH3sGRsTXxkWXU32SykjV/nVZQTEdb98T+6HBWtEULTboV8ucnQeWMwVEAsKU6OrDr0wQYCZjBMSkOVmv5QiggR5knJYhr0UrqsLVQu4y1kADOGEwrYSBORYtSSPEbcahADfvZXuk/QJoBCfyHgPRjn+A6bwycQrBjZ0DvNSlo90HD+O5qD6AWcLXrkTeWDjopAsgiwS9gk9ywwvgv3Ti+HOPKWysTK8Ig/Wn279rbGstnUsDeS514ptEDTORLDAXqAcAyqW4mUQaQ68jM8hSop+AdPkhQJxv+6lJv6/FxciHJgYmO9WoQNAbzMoNFYYwM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/A-Book-of-Operas-Their-Histories-Their-Plots-and-Their-Music_5724
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy